# Generated by Django 5.2.11 on 2026-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pokemon_images"),
        ),
    ]
