# Generated by Django 5.2.11 on 2026-03-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0002_pokemon_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PokemonEntity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(verbose_name="Широта")),
                ("lon", models.FloatField(verbose_name="Долгота")),
                (
                    "pokemon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="pokemon_entities.pokemon",
                    ),
                ),
            ],
        ),
    ]
