# Generated by Django 5.2.11 on 2026-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0003_pokemonentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время появления"
            ),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время исчезновения"
            ),
        ),
    ]
