# Generated by Django 5.2.11 on 2026-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0004_pokemonentity_appeared_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="defence",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Защита"),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Здоровье"),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Уровень"),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Выносливость"
            ),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="strength",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Атака"),
        ),
    ]
