# Generated by Django 5.2.11 on 2026-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0005_pokemonentity_defence_pokemonentity_health_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
    ]
