# Generated by Django 5.2.11 on 2026-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0006_pokemon_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя (англ.)"
            ),
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Имя (яп.)"
            ),
        ),
    ]
