# Generated by Django 5.2.11 on 2026-03-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0008_pokemon_previous_evolution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pokemon",
            options={"verbose_name": "Покемон", "verbose_name_plural": "Покемоны"},
        ),
        migrations.AlterModelOptions(
            name="pokemonentity",
            options={
                "verbose_name": "Сущность покемона",
                "verbose_name_plural": "Сущности покемонов",
            },
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="pokemon_images",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Имя (рус.)"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="pokemon_entities.pokemon",
                verbose_name="Покемон",
            ),
        ),
    ]
